### ISSUE TITLE
Translation not working anymore

### ISSUE THREAD

**Issue by AlexanderWillner** [m9dfukc/deepl-alfred-workflow#14]
Seems that the translation API just returns ```DeepL no translation found```.

**Comment by chriskonnertz** [comment]
It does not return `"{"jsonrpc": "2.0","error":{"code":1042901,"message":"Too many requests."}}"`?

**Comment by m9dfukc** [comment]
Yeah, [this](https://github.com/chriskonnertz/DeepLy/issues/20) is probably related.
Would be a bummer as I use this workflow on a regular basis 👎 

I am quite busy right now but will have a look when there is some time left.

Thanks for reporting!

**Comment by andersennl** [comment]
I guess it's because the API access is limited to pro accounts [https://www.deepl.com/pro.html#api](https://www.deepl.com/pro.html#api).

**Comment by MahatmaFatalError** [comment]
If I get the pricing right the minimal price ist 20€ per month for API access. Seems not worth it for only occasional usage...

**Comment by andersennl** [comment]
Yes, I’ve switched to google translate api, which is 20$ for 1.000.000 translated characters.

**Comment by AlexanderWillner** [comment]
Very quick and dirty workaround: https://github.com/AlexanderWillner/deepl-alfred-workflow2

**Comment by m9dfukc** [comment]
Looks like the API has changed, see https://github.com/chriskonnertz/DeepLy/issues/20. For now I recommend to use the Workflow by @AlexanderWillner https://github.com/AlexanderWillner/deepl-alfred-workflow2.

I might update this workflow when [DeepLy v2 ](https://github.com/chriskonnertz/DeepLy/tree/2.0) is ready!

**Comment by m9dfukc** [comment]
Version 1.3.0 works again! Thanks a lot to @chriskonnertz for updating DeepLy!

**Comment by Goldsucher** [comment]
for me it isn't working with version 1.3.1.
"no translation found"
can someone confirm that?

**Comment by sutefan1** [comment]
It isn't working anympre for me as well. Same error : 
```{"jsonrpc": "2.0","error":{"code":1042901,"message":"Too many requests."}}```

I'm using Alfred v. 3.7 and this system infos:
```
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75
```

**Comment by AlexanderWillner** [comment]
@m9dfukc to see how to fix it, see my last changes. Let see if this is stable, however, „works for me“ so far.

**Comment by typoman** [comment]
Doesn't work here! `DeepL no translation found`. My PHP version is 7.1.16.
