### ISSUE TITLE
NoneType object has no attribute 'info'

### ISSUE THREAD

**Issue by josearmandojacq** [m9dfukc/deepl-alfred-workflow#15]
![screen shot 2018-07-24 at 11 49 17 am](https://user-images.githubusercontent.com/24357305/43130794-c20dc078-8f37-11e8-9cca-7a722190e26e.png)

Am i missing some configs???

**Comment by m9dfukc** [comment]
No, currently the Workflow is broken as Deepl has changed it's API. I might update this in the future when the new DeepLy v2 is out, see https://github.com/m9dfukc/deepl-alfred-workflow/issues/14.
