### ISSUE TITLE
Is it brocken?

### ISSUE THREAD

**Issue by BenRoe** [m9dfukc/deepl-alfred-workflow#17]
If i type "dl hello world" i get DeepL not translation found.
Or could be the problem that i have php7 installed.

<img width="623" alt="Bildschirmfoto 2019-03-12 um 21 25 16" src="https://user-images.githubusercontent.com/643834/54233547-7026e780-450d-11e9-84be-7b36d9a14b4a.png">

**Comment by m9dfukc** [comment]
Unfortunately this workflow is currently broken as Deepl has changed their Api. I have updated the readme with information about the current state. For the time being you can use [this workflow](https://github.com/AlexanderWillner/deepl-alfred-workflow2).
