### ISSUE TITLE
ERROR: input.scriptfilter Code 4

### ISSUE THREAD

**Issue by patowod** [m9dfukc/deepl-alfred-workflow#18]
Hi, the workflow stopped working. Previously…
…"dl word-to-translate." would show the translation. Now there is not result. Debugging shows: 
[2019-11-07 14:41:15][ERROR: input.scriptfilter] Code 4: parse error: Invalid numeric literal at line 2, column 0

The hardcoded example "dlfr" still works. If I change the language code form FR to EN there the translation works as it used to — so the problem only occurs when using the "dl" on it's own.

**Comment by m9dfukc** [comment]
Hey, thanks for the note ... If I have some free time I will give this another try. In the meantime you can checkout https://github.com/chriskonnertz/DeepLy or if you are using Alfred 4 https://github.com/alexander-heimbuch/deepl-alfred-workflow 

But be aware that Deepl introduced a Api limit and all libraries/tools that don't support their commercial endpoint might suffer "random" errors. There also is their newest App https://www.deepl.com/app which unfortunately doesn't fit my workflow :(
