### ISSUE TITLE
Support for multiple languages at the same time

### ISSUE THREAD

**Issue by robsalasco** [m9dfukc/deepl-alfred-workflow#3]
Hi! Thank you for your script.

Would be useful to have multiple translations in different languages with the same query :)!

**Comment by m9dfukc** [comment]
Hi,

this workflow was meant to substitute for the discontinued [Leo Dict Workflow](https://github.com/psistorm/alfredapp). 

Not sure how you would integrate such functionality and if it even makes sense for a broad range of users. Can you elaborate on how you imagine the workflow of this?!

**Comment by robsalasco** [comment]
It's the same funcionality found on [this](https://github.com/DONSA/alfred-google-translate) google translate workflow.

<img width="593" alt="captura de pantalla 2017-12-09 a la s 18 38 56" src="https://user-images.githubusercontent.com/2642107/33799733-4a0e0314-dd10-11e7-8f2d-3acbf673b2ce.png">

The user can add multiple languages at bottom.

Thank you @m9dfukc !
