### ISSUE TITLE
Larger preview area

### ISSUE THREAD

**Issue by jmuheim** [m9dfukc/deepl-alfred-workflow#5]
When translating sentences (which are the main purpose of using DeepL in my opinion), the suggestions are stripped way too much:

<img width="592" alt="screen shot 2018-01-16 at 11 05 54" src="https://user-images.githubusercontent.com/1814983/34983303-59e2faaa-faad-11e7-8007-45ed80bf9b56.png">

It would be great to have a larger preview for the currently selected suggestion.

**Comment by m9dfukc** [comment]
I'll look into this but I'm not sure if there is a way of multiline results in Alfred.
Have to dig through the Alfred docs ... on a first glance I haven't found anything.

**Comment by jmuheim** [comment]
The built-in clipboard history of Alfred has a good solution for this:

![image](https://user-images.githubusercontent.com/1814983/34984859-86feca46-fab2-11e7-8c67-2a47d9105044.png)

**Comment by m9dfukc** [comment]
Good hint. Thanks!

**Comment by jmuheim** [comment]
You're very welcome. Thank YOU for this nice workflow! 👍

**Comment by m9dfukc** [comment]
Unfortunately I didn't find a way to use the "spilt panel" feature which the build-in clipboard history uses. But I made a workaround, now you can use _[cmd]+_[enter]_ to show selected item as screen overlay, _[esc]_ brings you back to the selection list. If you just hit _[enter]_ you'll copy the translated text of selected item to the clipboard.
