### ISSUE TITLE
The following translation sequence isn't translated fully

### ISSUE THREAD

**Issue by jmuheim** [m9dfukc/deepl-alfred-workflow#6]
When trying to translate "In welcher Sprache möchten Sie kommunizieren? Meine Muttersprache ist Deutsch, aber ich spreche auch fliessend Englisch.", only the 2nd sentence (after the question mark) is translated:

![image](https://user-images.githubusercontent.com/1814983/34984562-a21c1b86-fab1-11e7-81ee-4bac93e0875d.png)

On the DeepL website, it works as expected:

![image](https://user-images.githubusercontent.com/1814983/34984619-d8c1915c-fab1-11e7-930d-4a08e70a6330.png)

**Comment by m9dfukc** [comment]
Yeah, definitely a bug. I'll check if the API response is already truncated or if this is on Alfred's side.
